
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var h={},k;for(k in c)c.hasOwnProperty(k)&&(h[k]=c[k]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var l=!1,m=!1,n=!1,aa=!1;l="object"===typeof window;m="function"===typeof importScripts;n="object"===typeof process&&"function"===typeof require&&!l&&!m;aa=!l&&!n&&!m;
if(c.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var q="";
if(n){q=__dirname+"/";var ba,ca;c.read=function(a,b){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof r))throw a;});process.on("unhandledRejection",t);c.quit=function(a){process.exit(a)};
c.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(l||m)m?q=self.location.href:document.currentScript&&
(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.lastIndexOf("/")+1):q="",c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||
0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},c.setWindowTitle=function(a){document.title=a};else throw Error("environment detection error");var u=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||u);for(k in h)h.hasOwnProperty(k)&&(c[k]=h[k]);h=void 0;assert("undefined"===typeof c.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"===typeof c.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof c.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof c.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");da=ea=x=function(){t("cannot use the stack before compiled code is ready to run, and has provided stack access")};
function y(a){fa||(fa={});fa[a]||(fa[a]=1,v(a))}var fa,ha={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&t("No WebAssembly support found. Build with -s WASM=0 to target JavaScript instead.");var z,ia=!1;function assert(a,b){a||t("Assertion failed: "+b)}function ja(a){var b=c["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function la(a,b,d,e){var f={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var d=(a.length<<2)+1,e=b=x(d);assert("number"==typeof d,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");ma(a,A,e,d)}return b},array:function(a){var b=x(a.length);assert(0<=a.length,"writeArrayToMemory array must have a length (should be an array or typed array)");na.set(a,b);return b}},g=ja(a),p=[];a=0;assert("array"!==b,'Return type should not be "array".');
if(e)for(var w=0;w<e.length;w++){var N=f[d[w]];N?(0===a&&(a=da()),p[w]=N(e[w])):p[w]=e[w]}d=g.apply(null,p);d=function(a){return"string"===b?oa(a):"boolean"===b?!!a:a}(d);0!==a&&ea(a);return d}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&pa)return pa.decode(a.subarray(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var p=a[b++]&63;224==(f&240)?f=(f&15)<<12|g<<6|p:(240!=(f&248)&&y("Invalid UTF-8 leading byte 0x"+f.toString(16)+" encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!"),f=(f&7)<<18|g<<12|p<<6|a[b++]&63);65536>f?e+=String.fromCharCode(f):(f-=
65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function oa(a){return a?qa(A,a,void 0):""}
function ma(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var p=a.charCodeAt(g);if(55296<=p&&57343>=p){var w=a.charCodeAt(++g);p=65536+((p&1023)<<10)|w&1023}if(127>=p){if(d>=e)break;b[d++]=p}else{if(2047>=p){if(d+1>=e)break;b[d++]=192|p>>6}else{if(65535>=p){if(d+2>=e)break;b[d++]=224|p>>12}else{if(d+3>=e)break;2097152<=p&&y("Invalid Unicode code point 0x"+p.toString(16)+" encountered when serializing a JS string to an UTF-8 string on the asm.js/wasm heap! (Valid unicode code points should be in range 0-0x1FFFFF).");
b[d++]=240|p>>18;b[d++]=128|p>>12&63}b[d++]=128|p>>6&63}b[d++]=128|p&63}}b[d]=0;return d-f}function ra(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function sa(a){var b=ra(a)+1,d=x(b);ma(a,na,d,b);return d}
function ta(a){return a.replace(/__Z[\w\d_]+/g,function(a){y("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return a===a?a:a+" ["+a+"]"})}function ua(){a:{var a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}c.extraStackTrace&&(a+="\n"+c.extraStackTrace());return ta(a)}function va(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,na,A,wa,B,C;
function xa(){c.HEAP8=na=new Int8Array(buffer);c.HEAP16=wa=new Int16Array(buffer);c.HEAP32=B=new Int32Array(buffer);c.HEAPU8=A=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=C=new Uint32Array(buffer);c.HEAPF32=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}assert(!0,"stack must start aligned");assert(!0,"heap must start aligned");c.TOTAL_STACK&&assert(5242880===c.TOTAL_STACK,"the stack size can no longer be determined at runtime");var D=c.TOTAL_MEMORY||16777216;
5242880>D&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+D+"! (TOTAL_STACK=5242880)");assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");
c.buffer?(buffer=c.buffer,assert(buffer.byteLength===D,"provided buffer should be "+D+" bytes, but it is "+buffer.byteLength)):("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(assert(0===D%65536),z=new WebAssembly.Memory({initial:D/65536}),buffer=z.buffer):buffer=new ArrayBuffer(D),assert(buffer.byteLength===D),c.buffer=buffer);xa();B[3180]=5255856;
function ya(){34821223==C[1313963]&&2310721022==C[1313962]||t("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x02135467, but received 0x"+C[1313962].toString(16)+" "+C[1313963].toString(16));if(1668509029!==B[0])throw"Runtime error: The application has corrupted its heap memory area (address zero)!";}B[0]=1668509029;wa[1]=25459;if(115!==A[2]||99!==A[3])throw"Runtime error: expected the system to be little-endian!";
function za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.Md;"number"===typeof d?void 0===b.Sa?c.dynCall_v(d):c.dynCall_vi(d,b.Sa):d(void 0===b.Sa?null:b.Sa)}}}var Aa=[],Ba=[],Ca=[],Fa=[],Ga=[],E=!1,F=!1;function Ha(){ya();E||(E=!0,za(Ba))}function Ia(){var a=c.preRun.shift();Aa.unshift(a)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var G=0,H=null,Ja=null,Ka={};
function La(){G++;c.monitorRunDependencies&&c.monitorRunDependencies(G);assert(!Ka["wasm-instantiate"]);Ka["wasm-instantiate"]=1;null===H&&"undefined"!==typeof setInterval&&(H=setInterval(function(){if(ia)clearInterval(H),H=null;else{var a=!1,b;for(b in Ka)a||(a=!0,v("still waiting on run dependencies:")),v("dependency: "+b);a&&v("(end of list)")}},1E4))}c.preloadedImages={};c.preloadedAudios={};
function Ma(){var a=I;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var I="cuddjs.wasm";if(!Ma()){var Na=I;I=c.locateFile?c.locateFile(Na,q):q+Na}function Oa(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(I);throw"both async and sync fetching of the wasm failed";}catch(a){t(a)}}
function Pa(){return c.wasmBinary||!l&&!m||"function"!==typeof fetch?new Promise(function(a){a(Oa())}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Oa()})}
function Ra(a){function b(a){c.asm=a.exports;G--;c.monitorRunDependencies&&c.monitorRunDependencies(G);assert(Ka["wasm-instantiate"]);delete Ka["wasm-instantiate"];0==G&&(null!==H&&(clearInterval(H),H=null),Ja&&(a=Ja,Ja=null,a()))}function d(a){assert(c===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;b(a.instance)}function e(a){Pa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){v("failed to asynchronously prepare wasm: "+
a);t(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ha};La();if(c.instantiateWasm)try{return c.instantiateWasm(f,b)}catch(p){return v("Module.instantiateWasm callback failed with error: "+p),!1}var g=c;c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ma()||"function"!==typeof fetch?e(d):WebAssembly.instantiateStreaming(fetch(I,{credentials:"same-origin"}),f).then(d,function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");
e(d)});return{}}c.asm=function(a,b){b.memory=z;b.table=new WebAssembly.Table({initial:39,maximum:39,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;a=Ra(b);assert(a,"binaryen setup failed (no wasm support?)");return a};var Sa=[function(){throw Error("Cuddjs just died");}];assert(!0);function Ta(a){c.___errno_location?B[c.___errno_location()>>2]=a:v("failed to set errno from JS");return a}
function Ua(a,b){for(var d=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),d++):d&&(a.splice(e,1),d--)}if(b)for(;d;d--)a.unshift("..");return a}function Va(a){var b="/"===a.charAt(0),d="/"===a.substr(-1);(a=Ua(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&d&&(a+="/");return(b?"/":"")+a}
function Wa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Xa(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Ya(){var a=Array.prototype.slice.call(arguments,0);return Va(a.join("/"))}function J(a,b){return Va(a+"/"+b)}
function Za(){for(var a="",b=!1,d=arguments.length-1;-1<=d&&!b;d--){b=0<=d?arguments[d]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ua(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ab=[];function bb(a,b){ab[a]={input:[],output:[],Ka:b};cb(a,db)}
var db={open:function(a){var b=ab[a.node.rdev];if(!b)throw new K(L.Ra);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ka.flush(a.tty)},flush:function(a){a.tty.Ka.flush(a.tty)},read:function(a,b,d,e){if(!a.tty||!a.tty.Ka.hb)throw new K(L.Za);for(var f=0,g=0;g<e;g++){try{var p=a.tty.Ka.hb(a.tty)}catch(w){throw new K(L.Xa);}if(void 0===p&&0===f)throw new K(L.lb);if(null===p||void 0===p)break;f++;b[d+g]=p}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){if(!a.tty||!a.tty.Ka.Va)throw new K(L.Za);
try{for(var f=0;f<e;f++)a.tty.Ka.Va(a.tty,b[d+f])}catch(g){throw new K(L.Xa);}e&&(a.node.timestamp=Date.now());return f}},eb={hb:function(a){if(!a.input.length){var b=null;if(n){var d=new Buffer(256),e=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(p){}}try{e=fs.readSync(f,d,0,256,null)}catch(p){if(-1!=p.toString().indexOf("EOF"))e=0;else throw p;}g&&fs.closeSync(f);0<e?b=d.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;d=Array(ra(b)+1);b=ma(b,d,0,d.length);d.length=b;a.input=d}return a.input.shift()},Va:function(a,b){null===b||10===b?(u(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(u(qa(a.output,0)),a.output=[])}},fb={Va:function(a,b){null===b||10===b?(v(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},
flush:function(a){a.output&&0<a.output.length&&(v(qa(a.output,0)),a.output=[])}},M={Da:null,Aa:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,d,e){if(24576===(d&61440)||4096===(d&61440))throw new K(L.pb);M.Da||(M.Da={dir:{node:{Ea:M.wa.Ea,Ca:M.wa.Ca,lookup:M.wa.lookup,La:M.wa.La,rename:M.wa.rename,unlink:M.wa.unlink,rmdir:M.wa.rmdir,readdir:M.wa.readdir,symlink:M.wa.symlink},stream:{Fa:M.ya.Fa}},file:{node:{Ea:M.wa.Ea,Ca:M.wa.Ca},stream:{Fa:M.ya.Fa,read:M.ya.read,write:M.ya.write,
$a:M.ya.$a,ib:M.ya.ib,kb:M.ya.kb}},link:{node:{Ea:M.wa.Ea,Ca:M.wa.Ca,readlink:M.wa.readlink},stream:{}},bb:{node:{Ea:M.wa.Ea,Ca:M.wa.Ca},stream:gb}});d=hb(a,b,d,e);16384===(d.mode&61440)?(d.wa=M.Da.dir.node,d.ya=M.Da.dir.stream,d.va={}):32768===(d.mode&61440)?(d.wa=M.Da.file.node,d.ya=M.Da.file.stream,d.za=0,d.va=null):40960===(d.mode&61440)?(d.wa=M.Da.link.node,d.ya=M.Da.link.stream):8192===(d.mode&61440)&&(d.wa=M.Da.bb.node,d.ya=M.Da.bb.stream);d.timestamp=Date.now();a&&(a.va[b]=d);return d},Nd:function(a){if(a.va&&
a.va.subarray){for(var b=[],d=0;d<a.za;++d)b.push(a.va[d]);return b}return a.va},Od:function(a){return a.va?a.va.subarray?a.va.subarray(0,a.za):new Uint8Array(a.va):new Uint8Array},cb:function(a,b){var d=a.va?a.va.length:0;d>=b||(b=Math.max(b,d*(1048576>d?2:1.125)|0),0!=d&&(b=Math.max(b,256)),d=a.va,a.va=new Uint8Array(b),0<a.za&&a.va.set(d.subarray(0,a.za),0))},yb:function(a,b){if(a.za!=b)if(0==b)a.va=null,a.za=0;else{if(!a.va||a.va.subarray){var d=a.va;a.va=new Uint8Array(new ArrayBuffer(b));d&&
a.va.set(d.subarray(0,Math.min(b,a.za)))}else if(a.va||(a.va=[]),a.va.length>b)a.va.length=b;else for(;a.va.length<b;)a.va.push(0);a.za=b}},wa:{Ea:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.za:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ga=4096;b.blocks=Math.ceil(b.size/
b.Ga);return b},Ca:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.yb(a,b.size)},lookup:function(){throw ib[L.nb];},La:function(a,b,d,e){return M.createNode(a,b,d,e)},rename:function(a,b,d){if(16384===(a.mode&61440)){try{var e=jb(b,d)}catch(g){}if(e)for(var f in e.va)throw new K(L.Ya);}delete a.parent.va[a.name];a.name=d;b.va[d]=a;a.parent=b},unlink:function(a,b){delete a.va[b]},rmdir:function(a,b){var d=jb(a,b),e;for(e in d.va)throw new K(L.Ya);
delete a.va[b]},readdir:function(a){var b=[".",".."],d;for(d in a.va)a.va.hasOwnProperty(d)&&b.push(d);return b},symlink:function(a,b,d){a=M.createNode(a,b,41471,0);a.link=d;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new K(L.Ia);return a.link}},ya:{read:function(a,b,d,e,f){var g=a.node.va;if(f>=a.node.za)return 0;a=Math.min(a.node.za-f,e);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),d);else for(e=0;e<a;e++)b[d+e]=g[f+e];return a},write:function(a,b,d,e,f,g){g&&y("file packager has copied file data into memory, but in memory growth we are forced to copy it again (see --no-heap-copy)");
g=!1;if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.va||a.va.subarray)){if(g)return assert(0===f,"canOwn must imply no weird position inside the file"),a.va=b.subarray(d,d+e),a.za=e;if(0===a.za&&0===f)return a.va=new Uint8Array(b.subarray(d,d+e)),a.za=e;if(f+e<=a.za)return a.va.set(b.subarray(d,d+e),f),e}M.cb(a,f+e);if(a.va.subarray&&b.subarray)a.va.set(b.subarray(d,d+e),f);else for(g=0;g<e;g++)a.va[f+g]=b[d+g];a.za=Math.max(a.za,f+e);return e},Fa:function(a,b,d){1===d?b+=a.position:
2===d&&32768===(a.node.mode&61440)&&(b+=a.node.za);if(0>b)throw new K(L.Ia);return b},$a:function(a,b,d){M.cb(a.node,b+d);a.node.za=Math.max(a.node.za,b+d)},ib:function(a,b,d,e,f,g,p){if(32768!==(a.node.mode&61440))throw new K(L.Ra);d=a.node.va;if(p&2||d.buffer!==b&&d.buffer!==b.buffer){if(0<f||f+e<a.node.za)d.subarray?d=d.subarray(f,f+e):d=Array.prototype.slice.call(d,f,f+e);a=!0;e=kb(e);if(!e)throw new K(L.ob);b.set(d,e)}else a=!1,e=d.byteOffset;return{Qd:e,Jd:a}},kb:function(a,b,d,e,f){if(32768!==
(a.node.mode&61440))throw new K(L.Ra);if(f&2)return 0;M.ya.write(a,b,0,e,d,!1);return 0}}},O={Oa:!1,Ab:function(){O.Oa=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);O.eb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ab:function(a){return Buffer.Qa?Buffer.from(a):new Buffer(a)},Aa:function(a){assert(n);return O.createNode(null,"/",O.gb(a.Ua.root),0)},createNode:function(a,b,d){if(16384!==(d&61440)&&
32768!==(d&61440)&&40960!==(d&61440))throw new K(L.Ia);a=hb(a,b,d);a.wa=O.wa;a.ya=O.ya;return a},gb:function(a){try{var b=fs.lstatSync(a);O.Oa&&(b.mode=b.mode|(b.mode&292)>>2)}catch(d){if(!d.code)throw d;throw new K(L[d.code]);}return b.mode},Ba:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Aa.Ua.root);b.reverse();return Ya.apply(null,b)},qb:function(a){a&=-2656257;var b=0,d;for(d in O.eb)a&d&&(b|=O.eb[d],a^=d);if(a)throw new K(L.Ia);return b},wa:{Ea:function(a){a=O.Ba(a);
try{var b=fs.lstatSync(a)}catch(d){if(!d.code)throw d;throw new K(L[d.code]);}O.Oa&&!b.Ga&&(b.Ga=4096);O.Oa&&!b.blocks&&(b.blocks=(b.size+b.Ga-1)/b.Ga|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Ga:b.Ga,blocks:b.blocks}},Ca:function(a,b){var d=O.Ba(a);try{void 0!==b.mode&&(fs.chmodSync(d,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(d,b.size)}catch(e){if(!e.code)throw e;throw new K(L[e.code]);
}},lookup:function(a,b){var d=J(O.Ba(a),b);d=O.gb(d);return O.createNode(a,b,d)},La:function(a,b,d,e){a=O.createNode(a,b,d,e);b=O.Ba(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new K(L[f.code]);}return a},rename:function(a,b,d){a=O.Ba(a);b=J(O.Ba(b),d);try{fs.renameSync(a,b)}catch(e){if(!e.code)throw e;throw new K(L[e.code]);}},unlink:function(a,b){a=J(O.Ba(a),b);try{fs.unlinkSync(a)}catch(d){if(!d.code)throw d;throw new K(L[d.code]);
}},rmdir:function(a,b){a=J(O.Ba(a),b);try{fs.rmdirSync(a)}catch(d){if(!d.code)throw d;throw new K(L[d.code]);}},readdir:function(a){a=O.Ba(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new K(L[b.code]);}},symlink:function(a,b,d){a=J(O.Ba(a),b);try{fs.symlinkSync(d,a)}catch(e){if(!e.code)throw e;throw new K(L[e.code]);}},readlink:function(a){var b=O.Ba(a);try{return b=fs.readlinkSync(b),b=lb.relative(lb.resolve(a.Aa.Ua.root),b)}catch(d){if(!d.code)throw d;throw new K(L[d.code]);
}}},ya:{open:function(a){var b=O.Ba(a.node);try{32768===(a.node.mode&61440)&&(a.Ma=fs.openSync(b,O.qb(a.flags)))}catch(d){if(!d.code)throw d;throw new K(L[d.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Ma&&fs.closeSync(a.Ma)}catch(b){if(!b.code)throw b;throw new K(L[b.code]);}},read:function(a,b,d,e,f){if(0===e)return 0;try{return fs.readSync(a.Ma,O.ab(b.buffer),d,e,f)}catch(g){throw new K(L[g.code]);}},write:function(a,b,d,e,f){try{return fs.writeSync(a.Ma,O.ab(b.buffer),d,e,f)}catch(g){throw new K(L[g.code]);
}},Fa:function(a,b,d){if(1===d)b+=a.position;else if(2===d&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Ma).size}catch(e){throw new K(L[e.code]);}if(0>b)throw new K(L.Ia);return b}}},mb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",13:"Permission denied",14:"Bad address",
15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",35:"File locking deadlock error",
36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",54:"Exchange full",55:"No anode",
56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",75:"Value too large for defined data type",
76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",
93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"},L={pb:1,nb:2,wd:3,mc:4,Xa:5,Za:6,Cb:7,Nc:8,mb:9,Sb:10,lb:11,Gd:11,ob:12,Db:13,ec:14,Zc:15,Qb:16,dc:17,Hd:18,Ra:19,ad:20,oc:21,Ia:22,Ic:23,Ac:24,Ja:25,Dd:26,
fc:27,Vc:28,vd:29,sd:30,Bc:31,ld:32,ac:33,pd:34,Rc:42,jc:43,Tb:44,qc:45,rc:46,sc:47,yc:48,Ed:49,Lc:50,pc:51,Yb:35,Oc:37,Jb:52,Mb:53,Id:54,Jc:55,Nb:56,Ob:57,Zb:35,Pb:59,Xc:60,Mc:61,Ad:62,Wc:63,Sc:64,Tc:65,rd:66,Pc:67,Gb:68,xd:69,Ub:70,md:71,Dc:72,bc:73,Lb:74,ed:76,Kb:77,qd:78,tc:79,uc:80,xc:81,wc:82,vc:83,Yc:38,Ya:39,Ec:36,zc:40,gd:95,kd:96,Xb:104,Kc:105,Hb:97,od:91,cd:88,Uc:92,td:108,Wb:111,Eb:98,Vb:103,Hc:101,Fc:100,Bd:110,hc:112,ic:113,lc:115,Ib:114,$b:89,Cc:90,nd:93,ud:94,Fb:99,Gc:102,nc:106,$c:107,
Cd:109,Fd:87,cc:122,yd:116,dd:95,Qc:123,kc:84,hd:75,Rb:125,bd:131,jd:130,zd:86},nb=null,ob={},P=[],pb=1,qb=null,rb=!0,sb={},K=null,ib={};
function Q(a,b){a=Za("/",a);b=b||{};if(!a)return{path:"",node:null};var d={fb:!0,Wa:0},e;for(e in d)void 0===b[e]&&(b[e]=d[e]);if(8<b.Wa)throw new K(40);a=Ua(a.split("/").filter(function(a){return!!a}),!1);var f=nb;d="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=jb(f,a[e]);d=J(d,a[e]);f.Pa&&(!g||g&&b.fb)&&(f=f.Pa.root);if(!g||b.Na)for(g=0;40960===(f.mode&61440);)if(f=tb(d),d=Za(Wa(d),f),f=Q(d,{Wa:b.Wa}).node,40<g++)throw new K(40);}return{path:d,node:f}}
function ub(a){for(var b;;){if(a===a.parent)return a=a.Aa.jb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function vb(a,b){for(var d=0,e=0;e<b.length;e++)d=(d<<5)-d+b.charCodeAt(e)|0;return(a+d>>>0)%qb.length}function wb(a){var b=vb(a.parent.id,a.name);a.ub=qb[b];qb[b]=a}function jb(a,b){var d;if(d=(d=xb(a,"x"))?d:a.wa.lookup?0:13)throw new K(d,a);for(d=qb[vb(a.id,b)];d;d=d.ub){var e=d.name;if(d.parent.id===a.id&&e===b)return d}return a.wa.lookup(a,b)}
function hb(a,b,d,e){yb||(yb=function(a,b,d,e){a||(a=this);this.parent=a;this.Aa=a.Aa;this.Pa=null;this.id=pb++;this.name=b;this.mode=d;this.wa={};this.ya={};this.rdev=e},yb.prototype={},Object.defineProperties(yb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new yb(a,b,d,e);wb(a);return a}
var zb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ab(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function xb(a,b){if(rb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Bb(a,b){try{return jb(a,b),17}catch(d){}return xb(a,"wx")}
function Cb(){var a=4096;for(var b=0;b<=a;b++)if(!P[b])return b;throw new K(24);}function Db(a){Fb||(Fb=function(){},Fb.prototype={},Object.defineProperties(Fb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var b=new Fb,d;for(d in a)b[d]=a[d];a=b;b=Cb();a.fd=b;return P[b]=a}var gb={open:function(a){a.ya=ob[a.node.rdev].ya;a.ya.open&&a.ya.open(a)},Fa:function(){throw new K(29);}};function cb(a,b){ob[a]={ya:b}}
function Gb(a,b){var d="/"===b,e=!b;if(d&&nb)throw new K(16);if(!d&&!e){var f=Q(b,{fb:!1});b=f.path;f=f.node;if(f.Pa)throw new K(16);if(16384!==(f.mode&61440))throw new K(20);}b={type:a,Ua:{},jb:b,tb:[]};a=a.Aa(b);a.Aa=b;b.root=a;d?nb=a:f&&(f.Pa=b,f.Aa&&f.Aa.tb.push(b))}function Hb(a,b,d){var e=Q(a,{parent:!0}).node;a=Xa(a);if(!a||"."===a||".."===a)throw new K(22);var f=Bb(e,a);if(f)throw new K(f);if(!e.wa.La)throw new K(1);return e.wa.La(e,a,b,d)}function R(a){Hb(a,16895,0)}
function Ib(a,b,d){"undefined"===typeof d&&(d=b,b=438);Hb(a,b|8192,d)}function Jb(a,b){if(!Za(a))throw new K(2);var d=Q(b,{parent:!0}).node;if(!d)throw new K(2);b=Xa(b);var e=Bb(d,b);if(e)throw new K(e);if(!d.wa.symlink)throw new K(1);d.wa.symlink(d,b,a)}function tb(a){a=Q(a).node;if(!a)throw new K(2);if(!a.wa.readlink)throw new K(22);return Za(ub(a.parent),a.wa.readlink(a))}
function Kb(a,b){if(""===a)throw new K(2);if("string"===typeof b){var d=zb[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}var e=b&64?("undefined"===typeof e?438:e)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Va(a);try{f=Q(a,{Na:!(b&131072)}).node}catch(p){}}d=!1;if(b&64)if(f){if(b&128)throw new K(17);}else f=Hb(a,e,0),d=!0;if(!f)throw new K(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new K(20);if(!d&&(e=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==Ab(b)||b&512)?21:xb(f,Ab(b)):2))throw new K(e);if(b&512){e=f;var g;"string"===typeof e?g=Q(e,{Na:!0}).node:g=e;if(!g.wa.Ca)throw new K(1);if(16384===(g.mode&61440))throw new K(21);if(32768!==(g.mode&61440))throw new K(22);if(e=xb(g,"w"))throw new K(e);g.wa.Ca(g,{size:0,timestamp:Date.now()})}b&=-641;f=Db({node:f,path:ub(f),flags:b,seekable:!0,position:0,ya:f.ya,Bb:[],error:!1});f.ya.open&&f.ya.open(f);!c.logReadFiles||b&1||(Mb||(Mb={}),a in Mb||(Mb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{sb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),sb.onOpenFile(a,g))}catch(p){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return f}function Nb(a){if(null===a.fd)throw new K(9);a.Ta&&(a.Ta=null);try{a.ya.close&&a.ya.close(a)}catch(b){throw b;}finally{P[a.fd]=null}a.fd=null}
function Ob(a,b,d){if(null===a.fd)throw new K(9);if(!a.seekable||!a.ya.Fa)throw new K(29);if(0!=d&&1!=d&&2!=d)throw new K(22);a.position=a.ya.Fa(a,b,d);a.Bb=[]}
function Pb(){K||(K=function(a,b){this.node=b;this.zb=function(a){this.Ha=a;for(var b in L)if(L[b]===a){this.code=b;break}};this.zb(a);this.message=mb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0});this.stack&&(this.stack=ta(this.stack))},K.prototype=Error(),K.prototype.constructor=K,[2].forEach(function(a){ib[a]=new K(a);ib[a].stack="<generic error, no stack>"}))}var Qb;function Rb(a,b){var d=0;a&&(d|=365);b&&(d|=146);return d}
function Sb(a,b,d){a=J("/dev",a);var e=Rb(!!b,!!d);Tb||(Tb=64);var f=Tb++<<8|0;cb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,d,e,f){for(var g=0,p=0;p<f;p++){try{var w=b()}catch(Ea){throw new K(5);}if(void 0===w&&0===g)throw new K(11);if(null===w||void 0===w)break;g++;d[e+p]=w}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,e,f){for(var g=0;g<f;g++)try{d(b[e+g])}catch(Da){throw new K(5);}f&&(a.node.timestamp=Date.now());return g}});
Ib(a,e,f)}var Tb,S={},yb,Fb,Mb,T=0;function U(){T+=4;return B[T-4>>2]}function Ub(){var a=P[U()];if(!a)throw new K(L.mb);return a}function Vb(a,b){if(V){var d=W();X([Wb,d,a,b])}}function Y(){t()}var Xb=null,Yb=!1,Zb=!1,$b={Rd:[],Kd:{}},Wb="log-message";function ac(a,b){var d=new XMLHttpRequest;d.addEventListener("load",function(){var a=new Worker(window.URL.createObjectURL(new Blob([this.responseText],{type:"text/javascript"})));b&&b.call(void 0,a)},d);d.open("get",a,!1);d.send()}
function bc(a,b){W=Y;var d=new Date,e=d.getTime().toString()+"_"+Math.floor(100*Math.random()+1).toString();ac(a+"worker.js",function(b){Xb=b;Xb.addEventListener("error",function(a){console.log("TRACE WORKER ERROR:");console.log(a)},!1);Xb.postMessage({cmd:"configure",data_version:1,session_id:e,url:a});V=Yb=!0});X(["application-name",b]);X(["session-name",d.toISOString()])}function X(a){V&&Yb&&Xb.postMessage({cmd:"post",entry:a})}var V,W;
function cc(){if(V){var a={static_base:1024,stack_base:12976,stack_top:12976,stack_max:5255856,dynamic_base:5255856,dynamic_top:B[3180],total_memory:D},b=W();X(["memory-layout",b,a])}}Pb();qb=Array(4096);Gb(M,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");cb(259,{read:function(){return 0},write:function(a,b,d,p){return p}});Ib("/dev/null",259);bb(1280,eb);bb(1536,fb);Ib("/dev/tty",1280);Ib("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(n)try{var d=require("crypto");b=function(){return d.randomBytes(1)[0]}}catch(e){b=function(){return 256*Math.random()|0}}else b=function(){t("random_device")};Sb("random",
b);Sb("urandom",b);R("/dev/shm");R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");Gb({Aa:function(){var a=hb("/proc/self","fd",16895,73);a.wa={lookup:function(a,d){var b=P[+d];if(!b)throw new K(9);a={parent:null,Aa:{jb:"fake"},wa:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ba.unshift(function(){if(!c.noFSInit&&!Qb){assert(!Qb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Qb=!0;Pb();c.stdin=c.stdin;c.stdout=c.stdout;c.stderr=c.stderr;c.stdin?Sb("stdin",c.stdin):Jb("/dev/tty","/dev/stdin");c.stdout?Sb("stdout",null,c.stdout):Jb("/dev/tty","/dev/stdout");c.stderr?Sb("stderr",null,c.stderr):Jb("/dev/tty1","/dev/stderr");var a=Kb("/dev/stdin",
"r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Kb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Kb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Ca.push(function(){rb=!1});Fa.push(function(){Qb=!1;var a=c._fflush;a&&a(0);for(a=0;a<P.length;a++){var b=P[a];b&&Nb(b)}});Ba.unshift(function(){});Fa.push(function(){});if(n){var fs=require("fs"),lb=require("path");O.Ab()}c.emscripten_trace_configure=function(a,b){bc(a,b)};
c.emscripten_trace_configure_for_google_wtf=function(){window&&window.Qa?Zb=!0:console.log("GOOGLE WTF NOT AVAILABLE TO ENABLE")};c.emscripten_trace_enter_context=function(a){if(V){var b=W();X(["enter-context",b,a])}Zb&&(b=$b.cachedScopes[a],b||(b=window.Qa.trace.events.Ld(a),$b.cachedScopes[a]=b),a=b(),$b.scopeStack.push(a))};c.emscripten_trace_exit_context=function(){if(V){var a=W();X(["exit-context",a])}Zb&&(a=$b.scopeStack.pop(),window.Qa.trace.Pd(a))};c.emscripten_trace_log_message=Vb;
c.emscripten_trace_mark=function(a){if(V){var b=W();X([Wb,b,"MARK",a])}Zb&&window.Qa.trace.mark(a)};n?Y=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Y=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?Y=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?Y=function(){return performance.now()}:Y=Date.now;
var Z=c.asm({},{b:function(a){t("Stack overflow! Attempted to allocate "+a+" bytes on the stack, but stack has only "+(5255856-da()+a)+" bytes available!")},l:function(a){v("Invalid function pointer called with signature 'ii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");t(a)},k:function(a){v("Invalid function pointer called with signature 'iii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");t(a)},j:function(a){v("Invalid function pointer called with signature 'iiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");t(a)},i:function(a){v("Invalid function pointer called with signature 'vi'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");v("Build with ASSERTIONS=2 for more info.");t(a)},h:function(a){v("Invalid function pointer called with signature 'vii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
v("Build with ASSERTIONS=2 for more info.");t(a)},d:function(a,b,d,e){t("Assertion failed: "+oa(a)+", at: "+[b?oa(b):"unknown filename",d,e?oa(e):"unknown function"])},g:function(){},f:Ta,C:function(a,b){T=b;try{var d=Ub();U();var e=U(),f=U(),g=U();Ob(d,e,g);B[f>>2]=d.position;d.Ta&&0===e&&0===g&&(d.Ta=null);return 0}catch(p){return"undefined"!==typeof S&&p instanceof K||t(p),-p.Ha}},e:function(a,b){T=b;try{var d=Ub(),e=U();a:{var f=U();for(b=a=0;b<f;b++){var g=d,p=B[e+8*b>>2],w=B[e+(8*b+4)>>2],N=
void 0,Lb=na;if(0>w||0>N)throw new K(22);if(null===g.fd)throw new K(9);if(0===(g.flags&2097155))throw new K(9);if(16384===(g.node.mode&61440))throw new K(21);if(!g.ya.write)throw new K(22);g.flags&1024&&Ob(g,0,2);var Da="undefined"!==typeof N;if(!Da)N=g.position;else if(!g.seekable)throw new K(29);var $a=g.ya.write(g,Lb,p,w,N,void 0);Da||(g.position+=$a);try{if(g.path&&sb.onWriteToFile)sb.onWriteToFile(g.path)}catch(ka){console.log("FS.trackingDelegate['onWriteToFile']('"+g.path+"') threw an exception: "+
ka.message)}var Ea=$a;if(0>Ea){var Eb=-1;break a}a+=Ea}Eb=a}return Eb}catch(ka){return"undefined"!==typeof S&&ka instanceof K||t(ka),-ka.Ha}},B:function(a,b){T=b;try{U();var d=U();B[d>>2]=-1;B[d+4>>2]=-1;B[d+8>>2]=-1;B[d+12>>2]=-1;return 0}catch(e){return"undefined"!==typeof S&&e instanceof K||t(e),-e.Ha}},A:function(a,b){T=b;try{U();U();U();var d=U();d&&(B[d>>2]=-1,B[d+4>>2]=-1,B[d+8>>2]=-1,B[d+12>>2]=-1);return 0}catch(e){return"undefined"!==typeof S&&e instanceof K||t(e),-e.Ha}},z:function(a,b){T=
b;try{var d=Ub(),e=U();switch(e){case 21509:case 21505:return d.tty?0:-L.Ja;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-L.Ja;case 21519:if(!d.tty)return-L.Ja;var f=U();return B[f>>2]=0;case 21520:return d.tty?-L.Ia:-L.Ja;case 21531:a=f=U();if(!d.ya.rb)throw new K(25);return d.ya.rb(d,e,a);case 21523:return d.tty?0:-L.Ja;case 21524:return d.tty?0:-L.Ja;default:t("bad ioctl syscall "+e)}}catch(g){return"undefined"!==typeof S&&g instanceof K||t(g),-g.Ha}},y:function(a,
b){T=b;try{var d=Ub();Nb(d);return 0}catch(e){return"undefined"!==typeof S&&e instanceof K||t(e),-e.Ha}},x:function(){},w:function(){c.abort()},v:function(a){return Sa[a]()},u:function(){return D},t:function(a,b,d){A.set(A.subarray(b,b+d),a)},s:function(a){var b=D;assert(a>b);cc();if(2147418112<a)return v("Cannot enlarge memory, asked to go up to "+a+" bytes, but the limit is 2147418112 bytes!"),!1;for(var d=Math.max(b,16777216);d<a;)536870912>=d?d=va(2*d):(d=Math.min(va((3*d+2147483648)/4),2147418112),
d===b&&y("Cannot ask for more memory since we reached the practical limit in browsers (which is just below 2GB), so the request would have failed. Requesting only "+D));var e=va(d);var f=c.buffer.byteLength;try{var g=-1!==z.grow((e-f)/65536)?c.buffer=z.buffer:null}catch(p){console.error("emscripten_realloc_buffer: Attempted to grow from "+f+" bytes to "+e+" bytes, but got error: "+p),g=null}if(!g||g.byteLength!=d)return v("Failed to grow the heap from "+b+" bytes to "+d+" bytes, not enough memory!"),
g&&v("Expected to get back a buffer of size "+d+" bytes, but instead got back a buffer of size "+g.byteLength),!1;c.buffer=buffer=g;xa();D=d;C[3180]=a;Vb("Emscripten","Enlarging memory arrays from "+b+" to "+d);cc();return!0},c:function(a,b){if("function"===typeof c.onMalloc)c.onMalloc(a,b);if(V){var d=W();X(["allocate",d,a,b])}},r:function(a){if("function"===typeof c.onFree)c.onFree(a);if(V){var b=W();X(["free",b,a])}},q:function(a,b,d){if("function"===typeof c.onRealloc)c.onRealloc(a,b,d);if(V){var e=
W();X(["reallocate",e,a,b,d])}},p:function(a){dc(a)},o:function(a){switch(a){case 30:return 16384;case 85:return 131068;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;
case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;
case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}Ta(22);return-1},n:function(a){0!==a&&ec(a,0,16);return 0},m:function(a){t("Cannot enlarge memory arrays to size "+a+" bytes. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+D+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
a:12720},buffer),fc=Z.D;Z.D=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return fc.apply(null,arguments)};var hc=Z.E;Z.E=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return hc.apply(null,arguments)};
var ic=Z.F;Z.F=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return ic.apply(null,arguments)};var jc=Z.G;Z.G=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return jc.apply(null,arguments)};var kc=Z.H;
Z.H=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return kc.apply(null,arguments)};var lc=Z.I;Z.I=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return lc.apply(null,arguments)};var mc=Z.J;
Z.J=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return mc.apply(null,arguments)};var nc=Z.K;Z.K=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return nc.apply(null,arguments)};var oc=Z.L;
Z.L=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return oc.apply(null,arguments)};var pc=Z.M;Z.M=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return pc.apply(null,arguments)};var qc=Z.N;
Z.N=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return qc.apply(null,arguments)};var rc=Z.O;Z.O=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return rc.apply(null,arguments)};var sc=Z.P;
Z.P=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return sc.apply(null,arguments)};var tc=Z.Q;Z.Q=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return tc.apply(null,arguments)};var uc=Z.R;
Z.R=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return uc.apply(null,arguments)};var vc=Z.S;Z.S=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return vc.apply(null,arguments)};var wc=Z.T;
Z.T=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return wc.apply(null,arguments)};var xc=Z.U;Z.U=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return xc.apply(null,arguments)};var yc=Z.V;
Z.V=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return yc.apply(null,arguments)};var zc=Z.W;Z.W=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return zc.apply(null,arguments)};var Ac=Z.X;
Z.X=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ac.apply(null,arguments)};var Bc=Z.Y;Z.Y=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Bc.apply(null,arguments)};var Cc=Z.Z;
Z.Z=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Cc.apply(null,arguments)};var Dc=Z._;Z._=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Dc.apply(null,arguments)};var Ec=Z.$;
Z.$=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ec.apply(null,arguments)};var Fc=Z.aa;Z.aa=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Fc.apply(null,arguments)};var Gc=Z.ba;
Z.ba=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Gc.apply(null,arguments)};var Hc=Z.ca;Z.ca=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Hc.apply(null,arguments)};var Ic=Z.da;
Z.da=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ic.apply(null,arguments)};var Jc=Z.ea;Z.ea=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Jc.apply(null,arguments)};var Kc=Z.fa;
Z.fa=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Kc.apply(null,arguments)};var Lc=Z.ga;Z.ga=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Lc.apply(null,arguments)};var Mc=Z.ha;
Z.ha=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Mc.apply(null,arguments)};var Nc=Z.ia;Z.ia=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Nc.apply(null,arguments)};var Oc=Z.ka;
Z.ka=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Oc.apply(null,arguments)};var Pc=Z.la;Z.la=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Pc.apply(null,arguments)};var Qc=Z.ma;
Z.ma=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Qc.apply(null,arguments)};var Rc=Z.na;Z.na=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Rc.apply(null,arguments)};var Sc=Z.oa;
Z.oa=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Sc.apply(null,arguments)};var Tc=Z.pa;Z.pa=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Tc.apply(null,arguments)};var Uc=Z.ra;
Z.ra=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Uc.apply(null,arguments)};var Vc=Z.sa;Z.sa=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Vc.apply(null,arguments)};var Wc=Z.ta;
Z.ta=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Wc.apply(null,arguments)};var Xc=Z.ua;Z.ua=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Xc.apply(null,arguments)};c.asm=Z;
c.___errno_location=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.D.apply(null,arguments)};c._apply_and=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.E.apply(null,arguments)};
c._apply_conditioning=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.F.apply(null,arguments)};c._apply_equiv=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.G.apply(null,arguments)};
c._apply_existential_forget=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.H.apply(null,arguments)};
c._apply_implies=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.I.apply(null,arguments)};c._apply_ite=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.J.apply(null,arguments)};
c._apply_not=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.K.apply(null,arguments)};c._apply_or=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.L.apply(null,arguments)};
c._apply_renaming=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.M.apply(null,arguments)};
c._apply_universal_forget=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.N.apply(null,arguments)};
c._are_equivalent=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.O.apply(null,arguments)};c._create_copy=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.P.apply(null,arguments)};
c._create_false=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.Q.apply(null,arguments)};c._create_literal=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.R.apply(null,arguments)};
c._create_true=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.S.apply(null,arguments)};c._destroy=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.T.apply(null,arguments)};
c._dump_dot=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.U.apply(null,arguments)};c._fflush=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.V.apply(null,arguments)};
c._free=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.W.apply(null,arguments)};c._get_atom_of=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.X.apply(null,arguments)};
c._get_else_of=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.Y.apply(null,arguments)};c._get_error=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.Z.apply(null,arguments)};
c._get_size=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._.apply(null,arguments)};c._get_then_of=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.$.apply(null,arguments)};
c._init=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.aa.apply(null,arguments)};c._is_consistent=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ba.apply(null,arguments)};
c._is_false=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ca.apply(null,arguments)};c._is_internal_node=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.da.apply(null,arguments)};
c._is_true=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ea.apply(null,arguments)};c._llvm_bswap_i32=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.fa.apply(null,arguments)};
c._main=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ga.apply(null,arguments)};c._make_new_atom=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ha.apply(null,arguments)};
var kb=c._malloc=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ia.apply(null,arguments)},ec=c._memset=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ja.apply(null,arguments)};
c._peak_node_count=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ka.apply(null,arguments)};c._print_info=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.la.apply(null,arguments)};
c._referenced_count=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ma.apply(null,arguments)};c._sbrk=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.na.apply(null,arguments)};
c._set_debug_mode=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.oa.apply(null,arguments)};c._support=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.pa.apply(null,arguments)};
c.establishStackSpace=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ra.apply(null,arguments)};
var x=c.stackAlloc=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.sa.apply(null,arguments)},ea=c.stackRestore=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ta.apply(null,arguments)},
da=c.stackSave=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.ua.apply(null,arguments)};c.dynCall_vi=function(){assert(E,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!F,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.qa.apply(null,arguments)};
c.asm=Z;c.intArrayFromString||(c.intArrayFromString=function(){t("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.intArrayToString||(c.intArrayToString=function(){t("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.ccall||(c.ccall=function(){t("'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.cwrap=function(a,b,d){return function(){return la(a,b,d,arguments)}};
c.setValue||(c.setValue=function(){t("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getValue||(c.getValue=function(){t("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.allocate||(c.allocate=function(){t("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getMemory||(c.getMemory=function(){t("'getMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
c.AsciiToString||(c.AsciiToString=function(){t("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stringToAscii||(c.stringToAscii=function(){t("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.UTF8ArrayToString||(c.UTF8ArrayToString=function(){t("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.UTF8ToString||(c.UTF8ToString=function(){t("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.stringToUTF8Array||(c.stringToUTF8Array=function(){t("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stringToUTF8||(c.stringToUTF8=function(){t("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.lengthBytesUTF8||(c.lengthBytesUTF8=function(){t("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.UTF16ToString||(c.UTF16ToString=function(){t("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.stringToUTF16||(c.stringToUTF16=function(){t("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.lengthBytesUTF16||(c.lengthBytesUTF16=function(){t("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.UTF32ToString||(c.UTF32ToString=function(){t("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stringToUTF32||(c.stringToUTF32=function(){t("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.lengthBytesUTF32||(c.lengthBytesUTF32=function(){t("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.allocateUTF8||(c.allocateUTF8=function(){t("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stackTrace=ua;c.addOnPreRun||(c.addOnPreRun=function(){t("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addOnInit||(c.addOnInit=function(){t("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.addOnPreMain||(c.addOnPreMain=function(){t("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addOnExit||(c.addOnExit=function(){t("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addOnPostRun||(c.addOnPostRun=function(){t("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.writeStringToMemory||(c.writeStringToMemory=function(){t("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.writeArrayToMemory||(c.writeArrayToMemory=function(){t("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.writeAsciiToMemory||(c.writeAsciiToMemory=function(){t("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addRunDependency||(c.addRunDependency=function(){t("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
c.removeRunDependency||(c.removeRunDependency=function(){t("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});c.ENV||(c.ENV=function(){t("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.FS||(c.FS=function(){t("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.FS_createFolder||(c.FS_createFolder=function(){t("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});c.FS_createPath||(c.FS_createPath=function(){t("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
c.FS_createDataFile||(c.FS_createDataFile=function(){t("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});c.FS_createPreloadedFile||(c.FS_createPreloadedFile=function(){t("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
c.FS_createLazyFile||(c.FS_createLazyFile=function(){t("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});c.FS_createLink||(c.FS_createLink=function(){t("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
c.FS_createDevice||(c.FS_createDevice=function(){t("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});c.FS_unlink||(c.FS_unlink=function(){t("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});c.GL||(c.GL=function(){t("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.dynamicAlloc||(c.dynamicAlloc=function(){t("'dynamicAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.warnOnce||(c.warnOnce=function(){t("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.loadDynamicLibrary||(c.loadDynamicLibrary=function(){t("'loadDynamicLibrary' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.loadWebAssemblyModule||(c.loadWebAssemblyModule=function(){t("'loadWebAssemblyModule' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.getLEB||(c.getLEB=function(){t("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getFunctionTables||(c.getFunctionTables=function(){t("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.alignFunctionTables||(c.alignFunctionTables=function(){t("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.registerFunctions||(c.registerFunctions=function(){t("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.addFunction||(c.addFunction=function(){t("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.removeFunction||(c.removeFunction=function(){t("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getFuncWrapper||(c.getFuncWrapper=function(){t("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.prettyPrint||(c.prettyPrint=function(){t("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.makeBigInt||(c.makeBigInt=function(){t("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.dynCall||(c.dynCall=function(){t("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getCompilerSetting||(c.getCompilerSetting=function(){t("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stackSave||(c.stackSave=function(){t("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.stackRestore||(c.stackRestore=function(){t("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stackAlloc||(c.stackAlloc=function(){t("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.establishStackSpace||(c.establishStackSpace=function(){t("'establishStackSpace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.print||(c.print=function(){t("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.printErr||(c.printErr=function(){t("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getTempRet0||(c.getTempRet0=function(){t("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.setTempRet0||(c.setTempRet0=function(){t("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.Pointer_stringify||(c.Pointer_stringify=function(){t("'Pointer_stringify' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.writeStackCookie||(c.writeStackCookie=function(){t("'writeStackCookie' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.checkStackCookie||(c.checkStackCookie=function(){t("'checkStackCookie' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.abortStackOverflow||(c.abortStackOverflow=function(){t("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.ALLOC_NORMAL||Object.defineProperty(c,"ALLOC_NORMAL",{get:function(){t("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});c.ALLOC_STACK||Object.defineProperty(c,"ALLOC_STACK",{get:function(){t("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});c.ALLOC_DYNAMIC||Object.defineProperty(c,"ALLOC_DYNAMIC",{get:function(){t("'ALLOC_DYNAMIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
c.ALLOC_NONE||Object.defineProperty(c,"ALLOC_NONE",{get:function(){t("'ALLOC_NONE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};function r(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}r.prototype=Error();r.prototype.constructor=r;Ja=function Yc(){c.calledRun||Zc();c.calledRun||(Ja=Yc)};
c.callMain=function(a){assert(0==G,"cannot call main when async dependencies remain! (listen on __ATMAIN__)");assert(0==Aa.length,"cannot call main when preRun functions remain to be called");a=a||[];Ha();var b=a.length+1,d=x(4*(b+1));B[d>>2]=sa(c.thisProgram);for(var e=1;e<b;e++)B[(d>>2)+e]=sa(a[e-1]);B[(d>>2)+b]=0;try{var f=c._main(b,d,0);dc(f,!0)}catch(g){g instanceof r||("SimulateInfiniteLoop"==g?c.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),v("exception thrown: "+a),
c.quit(1,g)))}finally{}};
function Zc(a){function b(){if(!c.calledRun&&(c.calledRun=!0,!ia)){Ha();ya();za(Ca);if(c.onRuntimeInitialized)c.onRuntimeInitialized();c._main&&$c&&c.callMain(a);ya();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();Ga.unshift(b)}za(Ga)}}a=a||c.arguments;if(!(0<G)){assert(!0);C[1313963]=34821223;C[1313962]=2310721022;if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ia();za(Aa);0<G||c.calledRun||(c.setStatus?
(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);b()},1)):b(),ya())}}c.run=Zc;
function ad(){var a=u,b=v,d=!1;u=v=function(){d=!0};try{var e=c._fflush;e&&e(0);["stdout","stderr"].forEach(function(a){a="/dev/"+a;try{var b=Q(a,{Na:!0});a=b.path}catch(w){}var e={sb:!1,exists:!1,error:0,name:null,path:null,object:null,vb:!1,xb:null,wb:null};try{b=Q(a,{parent:!0}),e.vb=!0,e.xb=b.path,e.wb=b.node,e.name=Xa(a),b=Q(a,{Na:!0}),e.exists=!0,e.path=b.path,e.object=b.node,e.name=b.node.name,e.sb="/"===b.path}catch(w){e.error=w.Ha}e&&(b=ab[e.object.rdev])&&b.output&&b.output.length&&(d=!0)})}catch(f){}u=
a;v=b;d&&y("stdio streams had content in them that was not flushed. you should set EXIT_RUNTIME to 1 (see the FAQ), or make sure to emit a newline when you printf etc.")}
function dc(a,b){ad();if(!b||!c.noExitRuntime||0!==a){if(c.noExitRuntime)b||v("exit("+a+") called, but EXIT_RUNTIME is not set, so halting execution but not exiting the runtime or preventing further async execution (build with EXIT_RUNTIME=1, if you want a true shutdown)");else if(ia=!0,ya(),za(Fa),F=!0,c.onExit)c.onExit(a);c.quit(a,new r(a))}}var bd=[];
function t(a){if(c.onAbort)c.onAbort(a);void 0!==a?(u(a),v(a),a=JSON.stringify(a)):a="";ia=!0;var b="abort("+a+") at "+ua();bd&&bd.forEach(function(d){b=d(b,a)});throw b;}c.abort=t;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var $c=!0;c.noInitialRun&&($c=!1);c.noExitRuntime=!0;Zc();


  return Module;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    